services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: darkha03/mycount:dev
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    restart: always
    
