"""init

Revision ID: 882b12d6159d
Revises: 
Create Date: 2025-10-28 17:54:42.949756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882b12d6159d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_shares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        # Name the FK explicitly; don't drop unnamed constraints in batch mode
        batch_op.create_foreign_key(
            'fk_expense_shares_participant_id_plan_participants',
            'plan_participants', ['participant_id'], ['id'], ondelete='SET NULL'
        )

    with op.batch_alter_table('plan_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(
            'fk_plan_participants_user_id_users',
            'users', ['user_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_participants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plan_participants_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_plan_participants_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('name')

    with op.batch_alter_table('expense_shares', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expense_shares_participant_id_plan_participants', type_='foreignkey')
        batch_op.create_foreign_key('fk_expense_shares_participant_id_plan_participants', 'plan_participants', ['participant_id'], ['id'])
        batch_op.alter_column('participant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
