"""update expense model

Revision ID: c20eb4ea5a92
Revises: 882b12d6159d
Create Date: 2025-10-28 22:02:34.621522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20eb4ea5a92'
down_revision = '882b12d6159d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payer_name', sa.String(length=100), nullable=False))
        batch_op.alter_column('payer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(
            'fk_expenses_payer_id_users',
            'users', ['payer_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_payer_id_users', type_='foreignkey')
        batch_op.create_foreign_key('fk_expenses_payer_id_users', 'users', ['payer_id'], ['id'])
        batch_op.alter_column('payer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('payer_name')

    # ### end Alembic commands ###
